language: node_js
branches:
  only:
    - master
    - /^greenkeeper/.*$/
notifications:
  email: false
node_js:
  - '8.8'
script:
  - npm run build && npm run test:prod
after_success:
  - npm run report-coverage
  - npm run deploy-docs
  - npm run semantic-release
